name: Compile

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
    
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo 'TMPDIR=$env:SM_VERSION::1.10' >> $GITHUB_ENV
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Compile
        run: |
          cd build/addons/sourcemod/scripting
          ./spcomp -E superzombiefortress.sp -o ../plugins/superzombiefortress.smx